version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.dev.postgres
    container_name: zapslot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zapdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
